### ISSUE TITLE
Cannot load library

### ISSUE THREAD

**Issue by pchomik** [Wolox/wolox-ci#10]
Hello,

I tried to use wolox-ci but I have a problem to load it. I'm loading library as global library from git and loading it in implicit or explicit way.
I'm using:
* Jenkins: Jenkins ver. 2.121.3
* wolox-ci: from master
* project data: https://github.com/pchomik/wolox-test

Thanks in advance for help.

The error:
```
> git fetch --no-tags --progress https://github.com/pchomik/wolox-test.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision ae0f3ef15755619a26fc86be681373303741ae19 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ae0f3ef15755619a26fc86be681373303741ae19
Commit message: "Some try"
 > git rev-list --no-walk 594e6577864be3f2eee32425ab2a10fe51c5284a # timeout=10
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/var/jenkins_home/jobs/test/branches/master/builds/4/libs/wolox-ci/vars/woloxCi.groovy: 1: unable to resolve class Library ,  unable to find class for annotation
 @ line 1, column 1.
   @Library('wolox-ci')
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.recompile(GroovyClassLoader.java:761)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:718)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$TimingLoader.loadClass(CpsGroovyShell.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
	at org.jenkinsci.plugins.workflow.cps.global.UserDefinedGlobalVariable.getValue(UserDefinedGlobalVariable.java:54)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:3)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by bubbathump** [comment]
I'm getting the exact same error. Have you figured it out?

**Comment by gilesw** [comment]
Yep I'm having the same error. I've named the library wolox-ci but it seems to not be able to reference itself.

**Comment by NoNalTrX** [comment]
I'm having the same issue. Loading library from master. 

Jenkins ver. 2.138.2
wolox-ci: from master

Thanks for your help

**Comment by gilesw** [comment]
I got it to work in the end by removing the self reference. Turns out it really doesn't do what I was expecting and isn't really a general yaml interface to pipeline (which they did seem to say.) I think I might go back to a mixture of pipeline and jjb.

**Comment by oliveirasWell** [comment]
Any update?

**Comment by kathywar** [comment]
Yes, I'd like to use this as well but I'm getting the same error as the other posters.

**Comment by guitarrapc** [comment]
I've try wolox-ci on my Jenkins docker and solved `unable to resolve class Library, unable to find class for annotation`. Let me share my workaround with this issue.

You need 2 steps to wolox-ci work on your Jenkins.

**1. fix `unable to resolve class Library` via patch to Shared Library.**

Error caused because of wolox-ci's .groovy didn't load `org.jenkinsci.plugins.workflow.libs.Library`. So my quick fix is import it before calling `Library`. I've forked repo and made little changes.

Here's diff. https://github.com/guitarrapc/wolox-ci/compare/development...import

Now switch Jenkins Shared Library to your forked repo. 
Go to `Manage Jenkins > Configure System > Global Pipeline Libraries` and add library as follows.

* name: wolox-ci
* GitHub URL: https://github.com/guitarrapc/wolox-ci.git
* Default version: import (YOUR GIT BRANCH)

**2.  Add dependent plugins which wolox-ci groovy calling**

wolox-ci groovy using some plugins but they are not indicated on README. After you fix `unable to resolve class Library`, you'll see missing plugin errors on you job. Let's add dependent plugins.

Go to `Manage Jenkins > Manage Plugins` and add followings.

* pipeline utility steps (wolox use it to read YAML)
* AnsiColor (wolox use it for console output)

Finally, you can execute wolox's sample app https://github.com/Wolox/rails-bootstrap on your jenkins!

![image](https://user-images.githubusercontent.com/3856350/73230539-fc430b80-41c0-11ea-8bed-9dbcf7cc3328.png)

I hope this helps you.

## ref

Here's my repo to try wolox, just for your reference.

* wolox-ci fork: https://github.com/guitarrapc/wolox-ci/tree/import
* jenkins docker: https://github.com/guitarrapc/jenkins-lab/tree/master/wolox
